# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fdfe661c4b2c4ac96dd1a02128c62630c46848112d28c930ea46988fd72b9fac0c30e3099bc5205e3fb1474cde15f56fffb1a63f7102878adb7233d57bfde22

test:
  secret_key_base: edc200dded92e2c2c3b736567a51248f604618f86e753a215172ce653ce2994d39082146aced19d2568ce1a80d0a5932d106c59ea46b68f6327b1a16e8273c21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
